version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    ports:
    - "9200:9200"
    environment:
    - xpack.security.enabled=false
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.3
    ports:
    - "5044:5044"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    ports:
    - "5601:5601"
