- name: Tagging
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Tag the Old instances as zombie
      ec2_tag:
        resource: "{{ item.id }}"
        region: "eu-central-1"
        state: present
        tags:
          InstanceSt: zombie
      with_items: "{{ ec2.instances }}"
- name: Terminate instances
  hosts: tag_InstanceSt_zombie
  gather_facts: no
  tasks:
    - name: Get the facts about the zombie instances
      ec2_facts:
    - name: remove instance by instance id
      ec2:
        state: absent
        region: "eu-central-1"
        instance_ids: "{{ ec2.instance_id }}"
        wait: true
      delegate_to: localhost
