# Launch instances, runs some tasks
# and then terminate them

- name: Create an instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: test_key
    instance_type: t2.micro
    image: ami-7c4f7097
    region: eu-central-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
